table Sales_1998
	lineageTag: f2093f0c-0c21-49d0-9e49-b69a1cf1b2ee

	column EmployeeID
		dataType: int64
		formatString: 0
		lineageTag: cdab3aa0-ee80-4ee7-908b-981283f3a02f
		summarizeBy: count
		sourceColumn: EmployeeID

		annotation SummarizationSetBy = Automatic

	column RegionDescription
		dataType: string
		lineageTag: 9a4a3041-c942-4647-a38e-d002f9920e9c
		summarizeBy: none
		sourceColumn: RegionDescription

		annotation SummarizationSetBy = Automatic

	column CompanyName
		dataType: string
		lineageTag: f345dc98-2a31-43d9-be0f-e0f662f36c1d
		summarizeBy: none
		sourceColumn: CompanyName

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		formatString: 0
		lineageTag: 3c7312a4-5b9b-4dbd-8192-7671df2b67ef
		summarizeBy: sum
		sourceColumn: Year

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: string
		lineageTag: 1f0f2499-0001-463b-abd1-fbc3a72a4666
		summarizeBy: none
		sourceColumn: Month

		annotation SummarizationSetBy = Automatic

	column 'Total Quantity'
		dataType: int64
		formatString: 0
		lineageTag: 52c4ff2d-c074-4937-8d51-e3d1ac1d7285
		summarizeBy: sum
		sourceColumn: Total Quantity

		annotation SummarizationSetBy = Automatic

	column 'Total Sales'
		dataType: double
		lineageTag: 63b0f84c-d963-4ceb-9a51-72d9797720b0
		summarizeBy: sum
		sourceColumn: Total Sales

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition Sales_1998 = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\JoséAndrésBarriosJer\Downloads\data-transformation-in-power-bi\Datasets\Sales_1998.csv"),[Delimiter=",", Columns=7, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"EmployeeID", Int64.Type}, {"RegionDescription", type text}, {"Company Name", type text}, {"Year", Int64.Type}, {"Month", type text}, {"Total Quantity", Int64.Type}, {"Total Sales", type number}}),
				    #"Renamed Columns" = Table.RenameColumns(#"Changed Type",{{"Company Name", "CompanyName"}})
				in
				    #"Renamed Columns"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

