table Dim_StockItem
	lineageTag: 073cb0b0-f5b3-493c-a636-99bd867820a1

	column 'Stock Item Key'
		dataType: int64
		formatString: 0
		lineageTag: fa0b99a6-fc6e-4997-86eb-650eedda2387
		summarizeBy: none
		sourceColumn: Stock Item Key

		annotation SummarizationSetBy = Automatic

	column 'WWI Stock Item ID'
		dataType: int64
		formatString: 0
		lineageTag: 19137720-d2d0-4ba4-82c3-012885d5dcb6
		summarizeBy: none
		sourceColumn: WWI Stock Item ID

		annotation SummarizationSetBy = Automatic

	column 'Stock Item'
		dataType: string
		lineageTag: 3ec06e43-c08d-47e2-8121-de8c6abeebba
		summarizeBy: none
		sourceColumn: Stock Item

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isText":true}

	column Color
		dataType: string
		lineageTag: 13e22899-7672-4d1b-a053-49f739650579
		summarizeBy: none
		sourceColumn: Color

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isText":true}

	column 'Selling Package'
		dataType: string
		lineageTag: 6ce3fe62-5b73-408d-a3ae-3429e8ea1ac4
		summarizeBy: none
		sourceColumn: Selling Package

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isText":true}

	column 'Buying Package'
		dataType: string
		lineageTag: 9cb020d4-ff5e-42b9-8b5c-fdd8a3e85f95
		summarizeBy: none
		sourceColumn: Buying Package

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isText":true}

	column Brand
		dataType: string
		lineageTag: f000d01f-3a59-4565-aff3-02d00bac5e3a
		summarizeBy: none
		sourceColumn: Brand

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isText":true}

	column Size
		dataType: string
		lineageTag: 4a7d826c-c908-4c3f-a367-19b03895c578
		summarizeBy: none
		sourceColumn: Size

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isText":true}

	column 'Lead Time Days'
		dataType: int64
		formatString: 0
		lineageTag: f6cf94d8-7414-4c19-b55b-93d0842a5d35
		summarizeBy: none
		sourceColumn: Lead Time Days

		annotation SummarizationSetBy = Automatic

	column 'Quantity Per Outer'
		dataType: int64
		formatString: 0
		lineageTag: 7bc25087-a46d-43af-b4a3-9a50f7419c27
		summarizeBy: none
		sourceColumn: Quantity Per Outer

		annotation SummarizationSetBy = Automatic

	column 'Is Chiller Stock'
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 5e370dcb-0be6-4632-936b-1bc16f572387
		summarizeBy: none
		sourceColumn: Is Chiller Stock

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

	column Barcode
		dataType: string
		lineageTag: b583b70a-d1e3-40a2-a0e2-87f666c57563
		summarizeBy: none
		sourceColumn: Barcode

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isText":true}

	column 'Tax Rate'
		dataType: int64
		formatString: 0
		lineageTag: 21558eca-7c1c-4e0f-a7f3-22b8d772db91
		summarizeBy: none
		sourceColumn: Tax Rate

		annotation SummarizationSetBy = Automatic

	column 'Unit Price'
		dataType: double
		lineageTag: c2ff0f22-7f02-4462-a6db-7edd7765f649
		summarizeBy: none
		sourceColumn: Unit Price

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Typical Weight Per Unit'
		dataType: double
		lineageTag: 54558d41-2183-4076-a61b-9ff4077d32a5
		summarizeBy: none
		sourceColumn: Typical Weight Per Unit

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Photo
		dataType: string
		lineageTag: ab901473-6b4c-4fd8-9bb5-8520cdc86b42
		summarizeBy: none
		sourceColumn: Photo

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isText":true}

	column Discount
		dataType: string
		lineageTag: d7ed12c6-85dd-45ac-b053-d397ae3fdc2f
		summarizeBy: none
		sourceColumn: Discount

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isText":true}

	column 'Valid From'
		dataType: string
		lineageTag: aea09b95-ac78-473b-bc36-512294e8f84f
		summarizeBy: none
		sourceColumn: Valid From

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isText":true}

	column 'Valid To'
		dataType: string
		lineageTag: b7b26be1-6515-4e91-9bbf-000b9fa987b2
		summarizeBy: none
		sourceColumn: Valid To

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isText":true}

	column 'Lineage Key'
		dataType: int64
		formatString: 0
		lineageTag: 3dd2335d-d810-4ac7-bb6a-4613a36f4cc8
		summarizeBy: none
		sourceColumn: Lineage Key

		annotation SummarizationSetBy = Automatic

	column 'Recommended Retail Price'
		dataType: string
		lineageTag: 4ae2a844-a3d2-4195-8e20-11dec63d97fd
		summarizeBy: none
		sourceColumn: Recommended Retail Price

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isText":true}

	column 'Retail Price Clean' = SUBSTITUTE(Dim_StockItem[Recommended Retail Price],"?","")
		dataType: string
		lineageTag: 54b594c8-31fa-4e76-a7a7-13d5ecd3149b
		summarizeBy: none

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

	partition Dim_StockItem-c74337e1-dfb3-44ac-b0ea-812ba9cb0dff = m
		mode: import
		source =
				let
				    Source = WorldWideImportersDW,
				    #"C:\Users\lukeb\Documents\DataCamp\sme-dax-in-power-bi\datasets\WorldWideImportersDW\_DimStockItem csv" = Source{[#"Folder Path"="C:\Users\Public\Documents\Datasets\Ch 1,3 & 4\",Name="DimStockItem.csv"]}[Content],
				    #"Imported CSV" = Csv.Document(#"C:\Users\lukeb\Documents\DataCamp\sme-dax-in-power-bi\datasets\WorldWideImportersDW\_DimStockItem csv",[Delimiter=",", Columns=21, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Imported CSV",{{"Column1", type text}, {"Column2", type text}, {"Column3", type text}, {"Column4", type text}, {"Column5", type text}, {"Column6", type text}, {"Column7", type text}, {"Column8", type text}, {"Column9", type text}, {"Column10", type text}, {"Column11", type text}, {"Column12", type text}, {"Column13", type text}, {"Column14", type text}, {"Column15", type text}, {"Column16", type text}, {"Column17", type text}, {"Column18", type text}, {"Column19", type text}, {"Column20", type text}, {"Column21", type text}}),
				    #"Removed Top Rows" = Table.Skip(#"Changed Type",1),
				    #"Promoted Headers" = Table.PromoteHeaders(#"Removed Top Rows", [PromoteAllScalars=true]),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Promoted Headers",{{"Stock Item Key", Int64.Type}, {"WWI Stock Item ID", Int64.Type}, {"Stock Item", type text}, {"Color", type text}, {"Selling Package", type text}, {"Buying Package", type text}, {"Brand", type text}, {"Size", type text}, {"Lead Time Days", Int64.Type}, {"Quantity Per Outer", Int64.Type}, {"Is Chiller Stock", Int64.Type}, {"Barcode", type text}, {"Tax Rate", Int64.Type}, {"Unit Price", type number}, {"Recommended Retail Price", type text}, {"Typical Weight Per Unit", type number}, {"Photo", type text}, {"Discount", type text}, {"Valid From", type text}, {"Valid To", type text}, {"Lineage Key", Int64.Type}})
				in
				    #"Changed Type1"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Exception

