table Fact_PerformanceRating
	lineageTag: ebbc99be-be6e-491b-a0f6-c385c08ac170

	column PerformanceID
		dataType: string
		lineageTag: 084f9cf4-8f4b-46bb-afae-cf61aed6a356
		summarizeBy: none
		sourceColumn: PerformanceID

		annotation SummarizationSetBy = Automatic

	column EmployeeID
		dataType: string
		lineageTag: 673214fa-f821-45de-a384-004ec94c18f6
		summarizeBy: none
		sourceColumn: EmployeeID

		annotation SummarizationSetBy = Automatic

	column ReviewDate
		dataType: dateTime
		formatString: Long Date
		lineageTag: c7d9a159-ad25-4dd7-9681-b21585ed6e9d
		summarizeBy: none
		sourceColumn: ReviewDate

		variation Variation
			isDefault
			relationship: 88e19f9b-c514-489d-984a-100811cbaa61
			defaultHierarchy: LocalDateTable_dc789ef1-b1bb-43cd-8a5f-539bf32fa24b.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column EnvironmentSatisfaction
		dataType: int64
		formatString: 0
		lineageTag: f901cf40-a9b7-4b01-9255-362107b4d5c6
		summarizeBy: sum
		sourceColumn: EnvironmentSatisfaction

		annotation SummarizationSetBy = Automatic

	column JobSatisfaction
		dataType: int64
		formatString: 0
		lineageTag: 0be3f361-73f2-4a5f-bed1-d952ee4dce26
		summarizeBy: sum
		sourceColumn: JobSatisfaction

		annotation SummarizationSetBy = Automatic

	column RelationshipSatisfaction
		dataType: int64
		formatString: 0
		lineageTag: a1224a8e-1261-4493-a0e2-7aed667ec889
		summarizeBy: sum
		sourceColumn: RelationshipSatisfaction

		annotation SummarizationSetBy = Automatic

	column TrainingOpportunitiesWithinYear
		dataType: int64
		formatString: 0
		lineageTag: d6f97175-da5e-4707-a0a5-27374c96fb9a
		summarizeBy: sum
		sourceColumn: TrainingOpportunitiesWithinYear

		annotation SummarizationSetBy = Automatic

	column TrainingOpportunitiesTaken
		dataType: int64
		formatString: 0
		lineageTag: 9b9d2450-7b7c-4e12-9c99-4311cfff8248
		summarizeBy: sum
		sourceColumn: TrainingOpportunitiesTaken

		annotation SummarizationSetBy = Automatic

	column WorkLifeBalance
		dataType: int64
		formatString: 0
		lineageTag: 3818d731-1516-4724-a5be-1f8c05870715
		summarizeBy: sum
		sourceColumn: WorkLifeBalance

		annotation SummarizationSetBy = Automatic

	column SelfRating
		dataType: int64
		formatString: 0
		lineageTag: 3e39f093-c184-4f9d-bc71-8def4fff1db8
		summarizeBy: sum
		sourceColumn: SelfRating

		annotation SummarizationSetBy = Automatic

	column ManagerRating
		dataType: int64
		formatString: 0
		lineageTag: b29626bb-c14c-410d-ab2e-f9de33b14be5
		summarizeBy: sum
		sourceColumn: ManagerRating

		annotation SummarizationSetBy = Automatic

	partition Fact_PerformanceRating = m
		mode: import
		source =
				let
				  Source = Csv.Document(File.Contents("C:\Users\JoséAndrésBarriosJer\Downloads\case-study-hr-analytics-in-power-bi\Datasets\PerformanceRating.csv"), [Delimiter = ",", Columns = 11, Encoding = 65001, QuoteStyle = QuoteStyle.None]),
				  #"Promoted headers" = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),
				  #"Changed column type" = Table.TransformColumnTypes(#"Promoted headers", {{"PerformanceID", type text}, {"EmployeeID", type text}, {"ReviewDate", type date}, {"EnvironmentSatisfaction", Int64.Type}, {"JobSatisfaction", Int64.Type}, {"RelationshipSatisfaction", Int64.Type}, {"TrainingOpportunitiesWithinYear", Int64.Type}, {"TrainingOpportunitiesTaken", Int64.Type}, {"WorkLifeBalance", Int64.Type}, {"SelfRating", Int64.Type}, {"ManagerRating", Int64.Type}}, "en-US")
				in
				  #"Changed column type"

	annotation PBI_ResultType = Table

