table _Calculations
	lineageTag: 9a0c1318-e8bb-4a39-b648-16d152204f66

	measure TotalSales = SUM(Sales[LinePrice])
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: 571d2a44-25b5-4725-8691-f601bb8c7698

		changedProperty = FormatString

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	measure SalesCount = DISTINCTCOUNT(Sales[OrderNo])
		formatString: 0
		lineageTag: bb8bdbed-6a96-4d96-8faa-5a4f50444379

	measure TotalProfit = SUM(Sales[Profit])
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: e4b971cb-6234-4062-acc5-a1e516c420cd

		changedProperty = FormatString

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	measure ProfitMarginRatio = [TotalProfit] / [TotalSales]
		formatString: 0.00\ %;-0.00\ %;0.00\ %
		lineageTag: a359f496-c515-4eb6-a346-c9088a1b1b18

		changedProperty = FormatString

	measure TotalSales_w_increase =
			
			VAR increase = 0.05
			RETURN '_Calculations'[TotalSales] + ('_Calculations'[TotalSales] * increase)
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: 71e40523-d16a-4f04-aef4-ca051c752001

		changedProperty = FormatString

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	measure TotalProfit_x = ```
			
			SUMX ( Sales, Sales[ItemPrice] - Sales[ItemCost] )
			
			```
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: f182be34-35e3-4b70-bf80-d62ccab39d29

		changedProperty = FormatString

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	measure '2018 Bikes Revenue' =
			
			CALCULATE (
			   SUM(Sales[LinePrice]),
			    Sales[ProductCategory] = "Bikes",
			    YEAR ( Sales[OrderDate] ) = 2018
			)
		lineageTag: ed983fa1-f366-4383-a191-5f71cdd69a4e

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Column
		formatString: 0
		lineageTag: 5547fdec-08d6-4e89-81e1-1f252b0d5a92
		summarizeBy: sum
		isNameInferred
		sourceColumn: [Column]

		annotation SummarizationSetBy = Automatic

	partition _Calculations-3a53e6fe-27b0-464b-8845-7297598d4eac = calculated
		mode: import
		source = Row("Column", BLANK())

	annotation PBI_Id = d24361272b95492b8f96ba92bbdc25e5

	annotation 436ba87b-9c83-4389-a31b-ebd06a36be98 = {"Expression":""}

