table 'NAICS Code'
	lineageTag: bbb35d4a-3155-4697-adef-63bb17de670e

	column 'NAICS code description'
		dataType: string
		lineageTag: 8d2c936d-bf2e-4a33-ad98-44e3cc73b487
		summarizeBy: none
		sourceColumn: NAICS code description

		annotation SummarizationSetBy = Automatic

	column 'NAICS code'
		dataType: int64
		formatString: 0
		lineageTag: 3f45a40b-26d3-4933-9e44-21e5c57c1805
		summarizeBy: none
		sourceColumn: NAICS code

		annotation SummarizationSetBy = Automatic

	partition 'NAICS Code' = m
		mode: import
		source =
				let
				    Source = Industry,
				    #"Removed Other Columns" = Table.SelectColumns(Source,{"NAICS code description", "NAICS code"}),
				    #"Removed Duplicates" = Table.Distinct(#"Removed Other Columns")
				in
				    #"Removed Duplicates"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

