table Timeseries_1979
	isHidden
	lineageTag: d4d5c253-48f9-4683-a66c-45ca7bd2e652

	column id
		dataType: string
		isHidden
		lineageTag: d4b3ce21-72dd-4749-97ac-cbcabe67055f
		summarizeBy: none
		sourceColumn: id

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Geographic Area Name'
		dataType: string
		isHidden
		lineageTag: b0bebbaa-def0-4a15-8388-5dfeb7ce324e
		summarizeBy: none
		sourceColumn: Geographic Area Name

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column '2012 NAICS Code'
		dataType: string
		isHidden
		lineageTag: 190ef76d-b937-457d-bb4e-a7e2c12aeefc
		summarizeBy: none
		sourceColumn: 2012 NAICS Code

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Meaning of NAICS code'
		dataType: string
		isHidden
		lineageTag: cc0be768-8900-417f-9960-2e3284de4457
		summarizeBy: none
		sourceColumn: Meaning of NAICS code

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Establishment age code'
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 8bc0fbb5-79b2-4727-ada0-ce4dc7efafb5
		summarizeBy: none
		sourceColumn: Establishment age code

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Meaning of Establishment age code'
		dataType: string
		isHidden
		lineageTag: d294f7bb-9dd3-4b6c-ba86-560c47a9ccca
		summarizeBy: none
		sourceColumn: Meaning of Establishment age code

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: e2d08981-6191-4fba-8026-512b0c00d3a3
		summarizeBy: none
		sourceColumn: Year

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Number of firms'
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: bb008644-2669-491c-87b8-8a099527830b
		summarizeBy: none
		sourceColumn: Number of firms

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Number of establishments'
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 46181661-79e3-44ae-95fc-59a50192dde6
		summarizeBy: none
		sourceColumn: Number of establishments

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Number of employees'
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 6d793bb2-88c1-4778-98eb-1a915249b5dd
		summarizeBy: none
		sourceColumn: Number of employees

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column '(DHS) denominator'
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 067dabba-62e5-43b4-ba49-c47c35ecbdc2
		summarizeBy: none
		sourceColumn: (DHS) denominator

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Number of establishments born during the last 12 months'
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 68ff4acf-00f1-4d16-819f-4f35c6d4c1a6
		summarizeBy: none
		sourceColumn: Number of establishments born during the last 12 months

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Rate of establishments born during the last 12 months'
		dataType: double
		isHidden
		lineageTag: 5ad7d321-6e97-412f-b800-864a1e739c93
		summarizeBy: none
		sourceColumn: Rate of establishments born during the last 12 months

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Number of establishments exited during the last 12 months'
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: ac3c05a6-8b70-4f74-8ed7-9630ce38e059
		summarizeBy: none
		sourceColumn: Number of establishments exited during the last 12 months

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Rate of establishments exited during the last 12 months'
		dataType: double
		isHidden
		lineageTag: 069fb188-7439-4928-8cb8-03684d64ce0c
		summarizeBy: none
		sourceColumn: Rate of establishments exited during the last 12 months

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Number of jobs created from expanding and opening establishments during the last 12 months'
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 24387b9e-bab3-43b8-adae-240f24a88b2a
		summarizeBy: none
		sourceColumn: Number of jobs created from expanding and opening establishments during the last 12 months

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Number of jobs created from opening establishments during the last 12 months'
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: f0fea488-c243-4ee6-9e18-43bdd8c26fd6
		summarizeBy: none
		sourceColumn: Number of jobs created from opening establishments during the last 12 months

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Number of jobs created from expanding establishments during the last 12 months'
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 3b916c58-813e-4ad8-a61c-afe69e869e14
		summarizeBy: none
		sourceColumn: Number of jobs created from expanding establishments during the last 12 months

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Rate of jobs created from opening establishments during the last 12 months'
		dataType: double
		isHidden
		lineageTag: 69d24b8a-88b5-4ca8-a2f4-5533e1b97805
		summarizeBy: none
		sourceColumn: Rate of jobs created from opening establishments during the last 12 months

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Rate of jobs created from expanding and opening establishments during the last 12 months'
		dataType: double
		isHidden
		lineageTag: 9832ae5d-5e08-4b3f-84ba-506e2795de3f
		summarizeBy: none
		sourceColumn: Rate of jobs created from expanding and opening establishments during the last 12 months

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Number of jobs lost from contracting and closing establishments during the last 12 months'
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 130267f8-a909-460e-90ba-774bc6babe9e
		summarizeBy: none
		sourceColumn: Number of jobs lost from contracting and closing establishments during the last 12 months

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Number of jobs lost from closing establishments during the last 12 months'
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 7f42a90d-1f61-48a9-9671-afe2845aa1bf
		summarizeBy: none
		sourceColumn: Number of jobs lost from closing establishments during the last 12 months

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Number of jobs lost from contracting establishments during the last 12 months'
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: d21c34e7-6c76-4074-987d-67f0fee92163
		summarizeBy: none
		sourceColumn: Number of jobs lost from contracting establishments during the last 12 months

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Rate of jobs lost from closing establishments during the last 12 months'
		dataType: double
		isHidden
		lineageTag: a859d123-12d8-4f66-b9db-50d4f928c0fc
		summarizeBy: none
		sourceColumn: Rate of jobs lost from closing establishments during the last 12 months

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Rate of jobs lost from contracting and closing establishments during the last 12 months'
		dataType: double
		isHidden
		lineageTag: 54cb0565-241e-40cf-b71b-46e62bb0a99a
		summarizeBy: none
		sourceColumn: Rate of jobs lost from contracting and closing establishments during the last 12 months

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Number of net jobs created from expanding/contracting and opening/closing establishments during the last 12 months'
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 2ef5b820-d1ab-4fa2-b452-2bffd90911b1
		summarizeBy: none
		sourceColumn: Number of net jobs created from expanding/contracting and opening/closing establishments during the last 12 months

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Rate of net jobs created from expanding/contracting and opening/closing establishments during the last 12 months'
		dataType: double
		isHidden
		lineageTag: 0f52a271-4ef5-443c-892b-48700fcef980
		summarizeBy: none
		sourceColumn: Rate of net jobs created from expanding/contracting and opening/closing establishments during the last 12 months

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Rate of reallocation during the last 12 months'
		dataType: double
		isHidden
		lineageTag: bb6f583c-eab7-4892-8cfe-dc03ef5b6153
		summarizeBy: none
		sourceColumn: Rate of reallocation during the last 12 months

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Number of firms that exited during the last 12 months'
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: ed476800-b676-4ef0-8bf7-fdfc717711a8
		summarizeBy: none
		sourceColumn: Number of firms that exited during the last 12 months

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Number of establishments associated with firm deaths during the last 12 months'
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 6dfb4cfa-3d48-42aa-90e5-143c83c224bc
		summarizeBy: none
		sourceColumn: Number of establishments associated with firm deaths during the last 12 months

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Number of employees associated with firm deaths during the last 12 months'
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: ddc708b9-3c4d-4761-b815-ef2e09d1de5e
		summarizeBy: none
		sourceColumn: Number of employees associated with firm deaths during the last 12 months

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	partition Timeseries_1979 = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\JoséAndrésBarriosJer\Downloads\data-modeling-in-power-bi\Datasets\Timeseries_1979.csv"),[Delimiter=",", Columns=31, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Column1", type text}, {"Column2", type text}, {"Column3", type text}, {"Column4", type text}, {"Column5", type text}, {"Column6", type text}, {"Column7", type text}, {"Column8", type text}, {"Column9", type text}, {"Column10", type text}, {"Column11", type text}, {"Column12", type text}, {"Column13", type text}, {"Column14", type text}, {"Column15", type text}, {"Column16", type text}, {"Column17", type text}, {"Column18", type text}, {"Column19", type text}, {"Column20", type text}, {"Column21", type text}, {"Column22", type text}, {"Column23", type text}, {"Column24", type text}, {"Column25", type text}, {"Column26", type text}, {"Column27", type text}, {"Column28", type text}, {"Column29", type text}, {"Column30", type text}, {"Column31", type text}}),
				    #"Removed Top Rows" = Table.Skip(#"Changed Type",1),
				    #"Promoted Headers" = Table.PromoteHeaders(#"Removed Top Rows", [PromoteAllScalars=true]),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Promoted Headers",{{"id", type text}, {"Geographic Area Name", type text}, {"2012 NAICS Code", type text}, {"Meaning of NAICS code", type text}, {"Establishment age code", Int64.Type}, {"Meaning of Establishment age code", type text}, {"Year", Int64.Type}, {"Number of firms", Int64.Type}, {"Number of establishments", Int64.Type}, {"Number of employees", Int64.Type}, {"(DHS) denominator", Int64.Type}, {"Number of establishments born during the last 12 months", Int64.Type}, {"Rate of establishments born during the last 12 months", type number}, {"Number of establishments exited during the last 12 months", Int64.Type}, {"Rate of establishments exited during the last 12 months", type number}, {"Number of jobs created from expanding and opening establishments during the last 12 months", Int64.Type}, {"Number of jobs created from opening establishments during the last 12 months", Int64.Type}, {"Number of jobs created from expanding establishments during the last 12 months", Int64.Type}, {"Rate of jobs created from opening establishments during the last 12 months", type number}, {"Rate of jobs created from expanding and opening establishments during the last 12 months", type number}, {"Number of jobs lost from contracting and closing establishments during the last 12 months", Int64.Type}, {"Number of jobs lost from closing establishments during the last 12 months", Int64.Type}, {"Number of jobs lost from contracting establishments during the last 12 months", Int64.Type}, {"Rate of jobs lost from closing establishments during the last 12 months", type number}, {"Rate of jobs lost from contracting and closing establishments during the last 12 months", type number}, {"Number of net jobs created from expanding/contracting and opening/closing establishments during the last 12 months", Int64.Type}, {"Rate of net jobs created from expanding/contracting and opening/closing establishments during the last 12 months", type number}, {"Rate of reallocation during the last 12 months", type number}, {"Number of firms that exited during the last 12 months", Int64.Type}, {"Number of establishments associated with firm deaths during the last 12 months", Int64.Type}, {"Number of employees associated with firm deaths during the last 12 months", Int64.Type}})
				in
				    #"Changed Type1"

	changedProperty = IsHidden

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

