table Time
	lineageTag: da1a1e4c-006d-46e2-b018-0f843f29b5b8

	column Year
		dataType: int64
		formatString: 0
		lineageTag: 47343052-8424-47fa-b349-6a7c6af46826
		summarizeBy: none
		sourceColumn: Year

		annotation SummarizationSetBy = Automatic

	column Decade
		dataType: int64
		formatString: 0
		lineageTag: 399200ed-d4fb-49e5-8928-c1e16f11509e
		summarizeBy: sum
		sourceColumn: Decade

		annotation SummarizationSetBy = Automatic

	column Century
		dataType: int64
		formatString: 0
		lineageTag: 7a0c1282-fda7-48ce-b7cf-959ab952d99c
		summarizeBy: sum
		sourceColumn: Century

		annotation SummarizationSetBy = Automatic

	partition Time = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\JoséAndrésBarriosJer\Downloads\data-modeling-in-power-bi\Datasets\Time.txt"),[Delimiter="	", Columns=3, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Year", Int64.Type}, {"Decade", Int64.Type}, {"Century", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

