table Timeseries_1980
	isHidden
	lineageTag: 3535fff6-9efe-4aea-8fa4-229bbaad10f7

	column id
		dataType: string
		isHidden
		lineageTag: 3459286f-8b62-4f6b-93b9-b2104ed56c4a
		summarizeBy: none
		sourceColumn: id

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Geographic Area Name'
		dataType: string
		isHidden
		lineageTag: dd3a02d0-e69c-4722-8458-34e80668494e
		summarizeBy: none
		sourceColumn: Geographic Area Name

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column '2012 NAICS Code'
		dataType: string
		isHidden
		lineageTag: c0d4f482-24ef-41e9-b13a-f13c14e5a0ff
		summarizeBy: none
		sourceColumn: 2012 NAICS Code

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Meaning of NAICS code'
		dataType: string
		isHidden
		lineageTag: 057d0293-f77c-44c9-bdd6-d266342da752
		summarizeBy: none
		sourceColumn: Meaning of NAICS code

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Establishment age code'
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: f7d53b42-ea0b-497a-b522-588111710c6d
		summarizeBy: none
		sourceColumn: Establishment age code

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Meaning of Establishment age code'
		dataType: string
		isHidden
		lineageTag: 61fbb92a-dce2-44e0-bc1d-b5a8b36ba777
		summarizeBy: none
		sourceColumn: Meaning of Establishment age code

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: c720ae76-9500-48fa-a82a-03458769165c
		summarizeBy: none
		sourceColumn: Year

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Number of firms'
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: b6bfbb8d-bd2f-4c56-a3d4-d3346a1a5dac
		summarizeBy: none
		sourceColumn: Number of firms

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Number of establishments'
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 85510ab9-c5de-43c9-a8bf-adb3494faa7b
		summarizeBy: none
		sourceColumn: Number of establishments

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Number of employees'
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: e42237b7-34da-43f2-9c8b-f74441be7d16
		summarizeBy: none
		sourceColumn: Number of employees

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column '(DHS) denominator'
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: ced1ddb0-ee5c-4e3e-bcc0-4e84c1f8515c
		summarizeBy: none
		sourceColumn: (DHS) denominator

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Number of establishments born during the last 12 months'
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 5f344cc5-4a4b-4f4d-9f3b-a0a13748bca0
		summarizeBy: none
		sourceColumn: Number of establishments born during the last 12 months

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Rate of establishments born during the last 12 months'
		dataType: double
		isHidden
		lineageTag: c44ff395-5d58-495c-bb5c-f63408f76de1
		summarizeBy: none
		sourceColumn: Rate of establishments born during the last 12 months

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Number of establishments exited during the last 12 months'
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: a330741a-8a6e-4223-8ef0-41d662e30bc9
		summarizeBy: none
		sourceColumn: Number of establishments exited during the last 12 months

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Rate of establishments exited during the last 12 months'
		dataType: double
		isHidden
		lineageTag: 64abe373-955d-4935-9fb1-e748cede48b7
		summarizeBy: none
		sourceColumn: Rate of establishments exited during the last 12 months

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Number of jobs created from expanding and opening establishments during the last 12 months'
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: ac31313a-52b6-4b3a-ae72-d312b8170664
		summarizeBy: none
		sourceColumn: Number of jobs created from expanding and opening establishments during the last 12 months

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Number of jobs created from opening establishments during the last 12 months'
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 4ec82717-2909-40da-98a7-982eb4dec4fa
		summarizeBy: none
		sourceColumn: Number of jobs created from opening establishments during the last 12 months

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Number of jobs created from expanding establishments during the last 12 months'
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 3b1fd4dd-0c0d-4bd0-bf5f-bd9640916a8a
		summarizeBy: none
		sourceColumn: Number of jobs created from expanding establishments during the last 12 months

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Rate of jobs created from opening establishments during the last 12 months'
		dataType: double
		isHidden
		lineageTag: 96f83bbc-52ee-417b-bd64-fc5accfdc1e9
		summarizeBy: none
		sourceColumn: Rate of jobs created from opening establishments during the last 12 months

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Rate of jobs created from expanding and opening establishments during the last 12 months'
		dataType: double
		isHidden
		lineageTag: 65a932bc-4a76-4d07-b302-e28929c51b16
		summarizeBy: none
		sourceColumn: Rate of jobs created from expanding and opening establishments during the last 12 months

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Number of jobs lost from contracting and closing establishments during the last 12 months'
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 82b423a0-e0aa-4754-91c1-f9ae02780d8f
		summarizeBy: none
		sourceColumn: Number of jobs lost from contracting and closing establishments during the last 12 months

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Number of jobs lost from closing establishments during the last 12 months'
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 1847c755-c23b-49cf-bcb4-68f4cebc6288
		summarizeBy: none
		sourceColumn: Number of jobs lost from closing establishments during the last 12 months

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Number of jobs lost from contracting establishments during the last 12 months'
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 29f88594-3abc-402f-9896-55d50ee04ab8
		summarizeBy: none
		sourceColumn: Number of jobs lost from contracting establishments during the last 12 months

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Rate of jobs lost from closing establishments during the last 12 months'
		dataType: double
		isHidden
		lineageTag: 9bc14a39-891b-4994-b51e-e34a8ff671ff
		summarizeBy: none
		sourceColumn: Rate of jobs lost from closing establishments during the last 12 months

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Rate of jobs lost from contracting and closing establishments during the last 12 months'
		dataType: double
		isHidden
		lineageTag: 184dfaed-ebd3-414b-8ccf-66be2681d5da
		summarizeBy: none
		sourceColumn: Rate of jobs lost from contracting and closing establishments during the last 12 months

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Number of net jobs created from expanding/contracting and opening/closing establishments during the last 12 months'
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 712ee9ac-13bc-446e-b806-564150a9138b
		summarizeBy: none
		sourceColumn: Number of net jobs created from expanding/contracting and opening/closing establishments during the last 12 months

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Rate of net jobs created from expanding/contracting and opening/closing establishments during the last 12 months'
		dataType: double
		isHidden
		lineageTag: 36505ca0-00c8-4d1c-b77b-dbfec8cfca3f
		summarizeBy: none
		sourceColumn: Rate of net jobs created from expanding/contracting and opening/closing establishments during the last 12 months

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Rate of reallocation during the last 12 months'
		dataType: double
		isHidden
		lineageTag: 5eaa36a0-754a-4e78-859a-6e8923136b33
		summarizeBy: none
		sourceColumn: Rate of reallocation during the last 12 months

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Number of firms that exited during the last 12 months'
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: ee30dc6b-579f-434f-9f46-f0ba2edfcf0d
		summarizeBy: none
		sourceColumn: Number of firms that exited during the last 12 months

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Number of establishments associated with firm deaths during the last 12 months'
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 65d92047-fe4a-4ad3-9b2a-47ff9222e055
		summarizeBy: none
		sourceColumn: Number of establishments associated with firm deaths during the last 12 months

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Number of employees associated with firm deaths during the last 12 months'
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: c4e6da4f-c261-467b-865c-d01ded2d48fa
		summarizeBy: none
		sourceColumn: Number of employees associated with firm deaths during the last 12 months

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	partition Timeseries_1980 = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\JoséAndrésBarriosJer\Downloads\data-modeling-in-power-bi\Datasets\Timeseries_1980.csv"),[Delimiter=",", Columns=31, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Column1", type text}, {"Column2", type text}, {"Column3", type text}, {"Column4", type text}, {"Column5", type text}, {"Column6", type text}, {"Column7", type text}, {"Column8", type text}, {"Column9", type text}, {"Column10", type text}, {"Column11", type text}, {"Column12", type text}, {"Column13", type text}, {"Column14", type text}, {"Column15", type text}, {"Column16", type text}, {"Column17", type text}, {"Column18", type text}, {"Column19", type text}, {"Column20", type text}, {"Column21", type text}, {"Column22", type text}, {"Column23", type text}, {"Column24", type text}, {"Column25", type text}, {"Column26", type text}, {"Column27", type text}, {"Column28", type text}, {"Column29", type text}, {"Column30", type text}, {"Column31", type text}}),
				    #"Removed Top Rows" = Table.Skip(#"Changed Type",1),
				    #"Promoted Headers" = Table.PromoteHeaders(#"Removed Top Rows", [PromoteAllScalars=true]),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Promoted Headers",{{"id", type text}, {"Geographic Area Name", type text}, {"2012 NAICS Code", type text}, {"Meaning of NAICS code", type text}, {"Establishment age code", Int64.Type}, {"Meaning of Establishment age code", type text}, {"Year", Int64.Type}, {"Number of firms", Int64.Type}, {"Number of establishments", Int64.Type}, {"Number of employees", Int64.Type}, {"(DHS) denominator", Int64.Type}, {"Number of establishments born during the last 12 months", Int64.Type}, {"Rate of establishments born during the last 12 months", type number}, {"Number of establishments exited during the last 12 months", Int64.Type}, {"Rate of establishments exited during the last 12 months", type number}, {"Number of jobs created from expanding and opening establishments during the last 12 months", Int64.Type}, {"Number of jobs created from opening establishments during the last 12 months", Int64.Type}, {"Number of jobs created from expanding establishments during the last 12 months", Int64.Type}, {"Rate of jobs created from opening establishments during the last 12 months", type number}, {"Rate of jobs created from expanding and opening establishments during the last 12 months", type number}, {"Number of jobs lost from contracting and closing establishments during the last 12 months", Int64.Type}, {"Number of jobs lost from closing establishments during the last 12 months", Int64.Type}, {"Number of jobs lost from contracting establishments during the last 12 months", Int64.Type}, {"Rate of jobs lost from closing establishments during the last 12 months", type number}, {"Rate of jobs lost from contracting and closing establishments during the last 12 months", type number}, {"Number of net jobs created from expanding/contracting and opening/closing establishments during the last 12 months", Int64.Type}, {"Rate of net jobs created from expanding/contracting and opening/closing establishments during the last 12 months", type number}, {"Rate of reallocation during the last 12 months", type number}, {"Number of firms that exited during the last 12 months", Int64.Type}, {"Number of establishments associated with firm deaths during the last 12 months", Int64.Type}, {"Number of employees associated with firm deaths during the last 12 months", Int64.Type}})
				in
				    #"Changed Type1"

	changedProperty = IsHidden

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

