table Northwind_products
	lineageTag: d5673b8f-d6c1-4277-be5b-1ed8eef82d04

	column CategoryName
		dataType: string
		lineageTag: c5a25246-f8c3-45be-8c30-7edb33a4687b
		summarizeBy: none
		sourceColumn: CategoryName

		annotation SummarizationSetBy = Automatic

	column AverageStock
		dataType: double
		lineageTag: 6930d0fe-580e-46c2-94a9-aae7065c8c8c
		summarizeBy: sum
		sourceColumn: AverageStock

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column ProductID
		dataType: double
		lineageTag: 999f0909-a0f1-4616-b113-63555d438f44
		summarizeBy: count
		sourceColumn: ProductID

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column ProductName
		dataType: string
		lineageTag: 6a3bb491-c83b-4412-8927-6484b2b469d3
		summarizeBy: none
		sourceColumn: ProductName

		annotation SummarizationSetBy = Automatic

	column UnitsInStock
		dataType: double
		lineageTag: 7c58acfd-275f-4a02-8323-0e0f15e98f58
		summarizeBy: sum
		sourceColumn: UnitsInStock

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column StockPercentDeviation
		dataType: double
		lineageTag: 086e9bd4-95bc-4e17-9834-432c085a6da2
		summarizeBy: sum
		sourceColumn: StockPercentDeviation

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition Northwind_products = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\JoséAndrésBarriosJer\Downloads\data-transformation-in-power-bi\Datasets\Northwind_products.csv"),[Delimiter=",", Columns=11, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"ProductID", Int64.Type}, {"ProductName", type text}, {"SupplierID", Int64.Type}, {"CategoryID", Int64.Type}, {"QuantityPerUnit", type text}, {"UnitPrice", type number}, {"UnitsInStock", Int64.Type}, {"UnitsOnOrder", Int64.Type}, {"ReorderLevel", Int64.Type}, {"Discontinued", type logical}, {"CategoryName", type text}}),
				    #"Sorted Rows" = Table.Sort(#"Changed Type",{{"UnitsInStock", Order.Descending}}),
				    #"Added Index" = Table.AddIndexColumn(#"Sorted Rows", "Index", 1, 1, Int64.Type),
				    #"Renamed Columns" = Table.RenameColumns(#"Added Index",{{"Index", "OverallStockRank"}}),
				    #"Grouped Rows" = Table.Group(#"Renamed Columns", {"CategoryName"}, {{"AverageStock", each List.Average([UnitsInStock]), type nullable number}, {"Grouped", each _, type table [ProductID=nullable number, ProductName=nullable text, SupplierID=nullable number, CategoryID=nullable number, QuantityPerUnit=nullable text, UnitPrice=nullable number, UnitsInStock=nullable number, UnitsOnOrder=nullable number, ReorderLevel=nullable number, Discontinued=nullable logical, CategoryName=nullable text, OverallStockRank=number]}}),
				    #"Expanded Grouped" = Table.ExpandTableColumn(#"Grouped Rows", "Grouped", {"ProductID", "ProductName", "UnitsInStock"}, {"ProductID", "ProductName", "UnitsInStock"}),
				    #"Added Custom" = Table.AddColumn(#"Expanded Grouped", "StockPercentDeviation", each [UnitsInStock] / [AverageStock]),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Added Custom",{{"StockPercentDeviation", Percentage.Type}})
				in
				    #"Changed Type1"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

