table 'NAICS Code'
	lineageTag: 4a13e07a-f69c-4185-84d4-c52502186d32

	column '2017 NAICS code'
		dataType: string
		lineageTag: 0e270a00-bcd1-4f91-a662-8a305ed2d49f
		summarizeBy: none
		sourceColumn: 2017 NAICS code

		annotation SummarizationSetBy = Automatic

	column 'Meaning of NAICS code'
		dataType: string
		lineageTag: ebfcf929-cb2f-4881-ac8d-044838cff3aa
		summarizeBy: none
		sourceColumn: Meaning of NAICS code

		annotation SummarizationSetBy = Automatic

	column 'Industry group'
		dataType: int64
		formatString: 0
		lineageTag: fdd9ddfe-fd7b-49c4-b967-afa3793d97af
		summarizeBy: sum
		sourceColumn: Industry group

		annotation SummarizationSetBy = Automatic

	column Sector
		dataType: int64
		formatString: 0
		lineageTag: ddaab574-4827-40f4-bb16-4830f2406f86
		summarizeBy: sum
		sourceColumn: Sector

		annotation SummarizationSetBy = Automatic

	column Subsector
		dataType: int64
		formatString: 0
		lineageTag: 101f890a-e58d-438b-91f3-472b754f64ba
		summarizeBy: sum
		sourceColumn: Subsector

		annotation SummarizationSetBy = Automatic

	column 'Industry level'
		dataType: int64
		formatString: 0
		lineageTag: fec5dea2-1919-47be-848b-8e29392d7bb8
		summarizeBy: sum
		sourceColumn: Industry level

		annotation SummarizationSetBy = Automatic

	partition 'NAICS Code-3522a18d-4a5b-4caa-901c-289e9b54d0b6' = m
		mode: import
		source =
				let
				    Source = Csv.Document(Web.Contents("https://assets.datacamp.com/production/repositories/6025/datasets/4491b55cb209c9babaed3f9bd1ea1600fefe64c2/NAICS%20Code.csv"),[Delimiter=",", Columns=19, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Column1", type text}, {"Column2", type text}, {"Column3", type text}, {"Column4", type text}, {"Column5", type text}, {"Column6", type text}, {"Column7", type text}, {"Column8", type text}, {"Column9", type text}, {"Column10", type text}, {"Column11", type text}, {"Column12", type text}, {"Column13", type text}, {"Column14", type text}, {"Column15", type text}, {"Column16", type text}, {"Column17", type text}, {"Column18", type text}, {"Column19", type text}}),
				    #"Removed Top Rows" = Table.Skip(#"Changed Type",1),
				    #"Promoted Headers" = Table.PromoteHeaders(#"Removed Top Rows", [PromoteAllScalars=true]),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Promoted Headers",{{"id", type text}, {"Geographic Area Name", type text}, {"Geo Footnote", type text}, {"2017 NAICS code", type text}, {"Industry group", Int64.Type}, {"2017 NAICS Footnote", type text}, {"Meaning of NAICS code", type text}, {"NAICS economic sector ", Int64.Type}, {"SUBSECTOR", Int64.Type}, {"Industry level", Int64.Type}, {"Year", Int64.Type}, {"Sales, value of shipments, or revenue ($1,000)", Int64.Type}, {"Relative standard error for estimate of sales, value of shipments, or revenue (%)", type number}, {"Annual payroll ($1,000)", Int64.Type}, {"First-quarter payroll ($1,000)", Int64.Type}, {"Number of employees", Int64.Type}, {"Production workers for pay period including March 12", Int64.Type}, {"Range indicating percent of total annual payroll imputed", type text}, {"Range indicating percent of total employees imputed", type text}}),
				    #"Removed Columns" = Table.RemoveColumns(#"Changed Type1",{"id", "Geographic Area Name", "Geo Footnote", "2017 NAICS Footnote"}),
				    #"Renamed Columns" = Table.RenameColumns(#"Removed Columns",{{"SUBSECTOR", "Subsector"}}),
				    #"Reordered Columns" = Table.ReorderColumns(#"Renamed Columns",{"2017 NAICS code", "Meaning of NAICS code", "Industry group", "NAICS economic sector ", "Subsector", "Industry level", "Year", "Sales, value of shipments, or revenue ($1,000)", "Relative standard error for estimate of sales, value of shipments, or revenue (%)", "Annual payroll ($1,000)", "First-quarter payroll ($1,000)", "Number of employees", "Production workers for pay period including March 12", "Range indicating percent of total annual payroll imputed", "Range indicating percent of total employees imputed"}),
				    #"Renamed Columns1" = Table.RenameColumns(#"Reordered Columns",{{"NAICS economic sector ", "Sector"}}),
				    #"Removed Columns1" = Table.RemoveColumns(#"Renamed Columns1",{"Year", "Sales, value of shipments, or revenue ($1,000)", "Relative standard error for estimate of sales, value of shipments, or revenue (%)", "Annual payroll ($1,000)", "First-quarter payroll ($1,000)", "Number of employees", "Production workers for pay period including March 12", "Range indicating percent of total annual payroll imputed", "Range indicating percent of total employees imputed"}),
				    #"Removed Duplicates" = Table.Distinct(#"Removed Columns1")
				in
				    #"Removed Duplicates"

	annotation PBI_ResultType = Table

